
modLoader="javafml"

loaderVersion="[28,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="foamdome"

version="${1.0.0}"

displayName="Foam Dome"

displayURL="http://example.com/"

logoFile="examplemod.png"

credits="DivineAspect for the Idea, Snurly for Textures!"

authors="Drizzs"

description='''

This is a Dome Creating mod, Using Foam Mekanisms you release foam in multiple different situations to get a Dome of different types!

'''