
modLoader="javafml"

loaderVersion="[28,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="foamdome"

version="${1.0.0}"


displayName="Foam Dome"

updateJSONURL="http://myurl.me/"

displayURL="http://example.com/"

logoFile="examplemod.png"

credits="DivineAspect for the Idea"

authors="Drizzs"

description='''
This makes domes underwater

'''