package com.drizzs.foamdome.util;

import com.drizzs.foamdome.FoamDome;
import com.drizzs.foamdome.domeblocks.*;
import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraftforge.common.ToolType;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

@Mod.EventBusSubscriber(modid = FoamDome.MOD_ID ,bus= Mod.EventBusSubscriber.Bus.MOD)
public class DomeRegistry
{

    @SubscribeEvent
    public static void registerBlocks(final RegistryEvent.Register<Block> event)
    {
        // Filler Blocks -- Transforms from Foam
        event.getRegistry().register(new Block(Block.Properties.create(Material.ROCK).harvestTool(ToolType.PICKAXE).hardnessAndResistance(30.0F, 600.0F).sound(SoundType.STONE)).setRegistryName("notfoam"));

        //Foam Generated by Dome and Tunnel Creators
        event.getRegistry().register(new Foam(Block.Properties.create(Material.SNOW).noDrops().tickRandomly().hardnessAndResistance(0).sound(SoundType.SNOW)).setRegistryName("foam"));
        event.getRegistry().register(new Foam(Block.Properties.create(Material.SNOW).noDrops().tickRandomly().hardnessAndResistance(0).sound(SoundType.SNOW)).setRegistryName("glassfoam"));
        event.getRegistry().register(new Foam(Block.Properties.create(Material.SNOW).noDrops().tickRandomly().hardnessAndResistance(0).sound(SoundType.SNOW)).setRegistryName("gravityfoam"));
        event.getRegistry().register(new Foam(Block.Properties.create(Material.SNOW).noDrops().tickRandomly().hardnessAndResistance(0).sound(SoundType.SNOW)).setRegistryName("hardgravityfoam"));
        event.getRegistry().register(new Foam(Block.Properties.create(Material.SNOW).noDrops().tickRandomly().hardnessAndResistance(0).sound(SoundType.SNOW)).setRegistryName("acidfoam"));

        //Dome Creators, Creates domes under different circumstance
        event.getRegistry().register(new DomeCreator(Block.Properties.create(Material.IRON).harvestTool(ToolType.PICKAXE).hardnessAndResistance(6).sound(SoundType.METAL)).setRegistryName("glassdomecreator"));
        event.getRegistry().register(new DomeCreator(Block.Properties.create(Material.IRON).harvestTool(ToolType.PICKAXE).hardnessAndResistance(6).sound(SoundType.METAL)).setRegistryName("domecreator"));
        event.getRegistry().register(new DomeCreator(Block.Properties.create(Material.IRON).harvestTool(ToolType.PICKAXE).tickRandomly().hardnessAndResistance(6).sound(SoundType.METAL)).setRegistryName("gravitydomecreator"));
        event.getRegistry().register(new DomeCreator(Block.Properties.create(Material.IRON).harvestTool(ToolType.PICKAXE).hardnessAndResistance(6).sound(SoundType.METAL)).setRegistryName("aciddomecreator"));

   //Tunnel Creators, Creates tunnels under different circumstances
        event.getRegistry().register(new TunnelCreator(Block.Properties.create(Material.IRON).harvestTool(ToolType.PICKAXE).hardnessAndResistance(6).sound(SoundType.METAL)).setRegistryName("glasstunnelcreator"));
        event.getRegistry().register(new TunnelCreator(Block.Properties.create(Material.IRON).harvestTool(ToolType.PICKAXE).hardnessAndResistance(6).sound(SoundType.METAL)).setRegistryName("tunnelcreator"));
        event.getRegistry().register(new TunnelCreator(Block.Properties.create(Material.IRON).harvestTool(ToolType.PICKAXE).hardnessAndResistance(6).sound(SoundType.METAL)).setRegistryName("airtunnelcreator"));
        event.getRegistry().register(new TunnelCreator(Block.Properties.create(Material.IRON).harvestTool(ToolType.PICKAXE).hardnessAndResistance(6).sound(SoundType.METAL)).setRegistryName("acidtunnelcreator"));

    }

    @SubscribeEvent
    public static void registerItems(final RegistryEvent.Register<Item> event)
    {
        event.getRegistry().register(new Item(new Item.Properties()).setRegistryName("foamicon"));
        event.getRegistry().register(new DomeItems(DomeLib.notfoam ,new Item.Properties().group(DomeGroup.instance)).setRegistryName("notfoam"));
        event.getRegistry().register(new DomeItems(DomeLib.domecreator ,new Item.Properties().group(DomeGroup.instance)).setRegistryName("domecreator"));
        event.getRegistry().register(new DomeItems(DomeLib.glassdomecreator ,new Item.Properties().group(DomeGroup.instance)).setRegistryName("glassdomecreator"));
        event.getRegistry().register(new DomeItems(DomeLib.gravitydomecreator ,new Item.Properties().group(DomeGroup.instance)).setRegistryName("gravitydomecreator"));
        event.getRegistry().register(new DomeItems(DomeLib.aciddomecreator ,new Item.Properties().group(DomeGroup.instance)).setRegistryName("aciddomecreator"));

        event.getRegistry().register(new DomeItems(DomeLib.tunnelcreator ,new Item.Properties().group(DomeGroup.instance)).setRegistryName("tunnelcreator"));
        event.getRegistry().register(new DomeItems(DomeLib.glasstunnelcreator ,new Item.Properties().group(DomeGroup.instance)).setRegistryName("glasstunnelcreator"));
        event.getRegistry().register(new DomeItems(DomeLib.airtunnelcreator ,new Item.Properties().group(DomeGroup.instance)).setRegistryName("airtunnelcreator"));
        event.getRegistry().register(new DomeItems(DomeLib.acidtunnelcreator ,new Item.Properties().group(DomeGroup.instance)).setRegistryName("acidtunnelcreator"));

    }

}
